'use client';
import { withBase } from './EthosPath';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { coaches, coachPortrait, type EthosCoach } from './EthosCoaches';
import EthosReveal from './EthosReveal';
import EthosButton from './EthosButton';
import EthosFooter from './EthosFooter';
const line = 'border-[#132040]/12';
export default function EthosCoachPage({coach}:{coach:EthosCoach}) {
 return <><main id="main-content"><section className="px-6 pb-20 pt-32 md:px-12 md:pt-40 lg:px-20"><div className="mx-auto max-w-[1280px]"><a href={withBase('/coaches')} className="mb-12 inline-flex items-center gap-3 text-[14px] text-[#132040]/70 hover:text-[#132040]"><ArrowLeft size={16} />All coaches</a><div className="grid items-center gap-12 md:grid-cols-[0.8fr_1.2fr] lg:gap-24"><EthosReveal><img src={withBase(coachPortrait(coach))} alt={coach.name} className="aspect-[4/5] w-full object-cover" /></EthosReveal><EthosReveal delay={0.1}><p className="font-accent text-[12px] uppercase tracking-[0.22em] text-[#9E1B34]">{coach.role}</p><h1 className="font-accent mt-6 text-[42px] leading-[1.08] lg:text-[64px]">{coach.name}</h1><p className="mt-5 text-[15px] leading-[1.8] text-[#132040]/70">{coach.credential}</p><div className="my-8 h-px w-16 bg-[#9E1B34]" /><p className="max-w-[520px] text-[24px] leading-[1.5] lg:text-[30px]">{coach.headline}</p><div className="mt-10"><EthosButton href={"/private-inquiry?coach=" + coach.slug}>Request a Discovery Call with {coach.name.split(" ")[0]}</EthosButton></div></EthosReveal></div></div></section>
 <section className="ethos-sand px-6 py-20 md:px-12 md:py-24 lg:px-20"><div className="mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-[1.1fr_0.9fr] lg:gap-24"><EthosReveal><p className="font-accent text-[12px] uppercase tracking-[0.24em] text-[#9E1B34]">Background and Perspective</p><h2 className="font-accent mt-6 text-[32px] leading-[1.15] md:text-[42px]">The experience behind the conversation.</h2>{coach.bio.map(p=><p key={p} className="mt-7 text-[17px] leading-[1.85] text-[#132040]/80">{p}</p>)}<div className={'mt-10 border-t pt-7 ' + line}><h3 className="font-accent text-[12px] uppercase tracking-[0.2em]">Areas of focus</h3><ul className="mt-5 flex flex-wrap gap-2">{coach.focus.map(f=><li key={f} className="border border-[#132040]/25 px-4 py-2 text-[14px]">{f}</li>)}</ul></div></EthosReveal><EthosReveal delay={0.1} className={'border-t pt-7 ' + line}><h2 className="text-[26px]">Credentials &amp; Experience</h2><dl className="mt-6">{coach.qualifications.map(([title,body])=><div key={title} className={'border-b py-6 ' + line}><dt className="text-[18px] leading-[1.5]">{title}</dt><dd className="ml-0 mt-2 text-[15px] leading-[1.7] text-[#132040]/70">{body}</dd></div>)}</dl><p className="font-accent mt-8 text-[11px] uppercase tracking-[0.18em] text-[#132040]/65">Professional background sources</p><div className="mt-4 flex flex-col items-start gap-3">{coach.sources.map(([label,url])=><a key={url} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 border-b border-[#132040]/30 pb-1 text-[14px]">{label}<ArrowUpRight size={14} /></a>)}</div></EthosReveal></div></section>
 <section className="px-6 py-20 md:px-12 lg:px-20"><div className="mx-auto max-w-[1280px]"><h2 className="font-accent text-[28px] md:text-[32px]">Meet our other coaches</h2><div className="mt-10 grid gap-8 md:grid-cols-2">{coaches.filter(c=>c.slug!==coach.slug).map(c=><a key={c.slug} href={withBase('/coaches/'+c.slug)} className={'group flex items-center gap-6 border-t pt-6 ' + line}><img src={withBase(coachPortrait(c))} alt="" loading="lazy" className="h-24 w-20 shrink-0 object-cover" /><div className="flex-1"><h3 className="text-[22px]">{c.name}</h3><p className="mt-2 text-[13px] uppercase tracking-[0.12em] text-[#9E1B34]">{c.role}</p></div><ArrowUpRight aria-hidden="true" size={20} className="transition-transform group-hover:-translate-y-1" /></a>)}</div></div></section></main><EthosFooter /></>;
}
