export const ethosSteps = [
 ['Private Inquiry', 'You reach out through the inquiry form or by email. A coach responds personally, promptly, and without scripts.'],
 ['The Discovery Call', 'Not a sales conversation. The coach is already working: reading, listening, and testing what you are solving for. The call closes with a mirror, the structure, and your decision.'],
 ['The Map', 'Session one lays out the whole journey: what comes next, how the work unfolds, and which assessments will be used. There are no surprises.'],
 ['The Work Itself', 'Baseline, blind spots, moonshot thinking, goals, implementation. Then a partnership that evolves as your life and your company evolve.'],
];
export const ethosFaqs = [
 ['Who is this for?', 'EthosQuest works exclusively with senior leaders: CEOs, founders, fund managers, and those who lead family enterprises. The person at the top is the single point of highest leverage in any organization: when their thinking clears, the business transforms. If you lead an organization and carry its final decisions, this work is built for you. If you are unsure whether you fit, reach out and a coach will give you an honest answer.'],
 ['What happens on the discovery call?', 'The discovery call is not a sales conversation. It is the first act of the methodology. The coach asks what is top of mind, listens for what is actually being said, and tests what you are solving for at the level of your life. The call closes in three moves: the coach mirrors back what was heard, explains the structure of the work, and you decide. The coach does not sell. The coach demonstrates.'],
 ['What does an engagement look like?', 'Three to four structured sessions a month on a weekly cadence, plus unlimited access between sessions: calls, texts, whatever is needed. Retainer-based, with the same structure for everyone. In the first ninety days the cadence is a floor, not a ceiling.'],
 ['What happens in the first ninety days?', 'Session one lays out the whole map. Weeks two to eight establish the baseline: the Wheel of Life across ten life domains, then best in class assessments for how others see you. Only once the baseline is real does the work move to moonshot thinking and goals. From day ninety onward, the engagement shifts to implementation.'],
 ['Which assessments do you use?', 'Best in class assessments in which our coaches are certified, as well as custom made assessments and exercises depending on each client’s needs. They are mirrors, not verdicts. The coach does not use them to tell you what is wrong. The coach uses them so you discover it yourself.'],
 ['Is this therapy?', 'No. Therapy is concerned with healing and looks backward. Coaching is concerned with clarity and forward movement. The coach does not diagnose or treat, and if a leader is in active crisis the coach recognizes it and refers to a licensed therapist. It is also not mentoring or consulting: the coach does not have an opinion about what you should do. The coach has a commitment to ensuring you see clearly, decide honestly, and act in alignment with what you value.'],
 ['What changes, and when?', 'Within three months, clients typically feel a fundamental difference in how they show up for themselves. Within six months, invariably, other people tell them they have changed. Change is not linear. Old patterns resurface under stress. The work is about mastery, not elimination.'],
 ['How is accountability handled?', 'You design it. The coach asks how you want to be held accountable, and you decide the intensity, the method, and the terms. Every time the coach holds you to it, the agreement is revisited. Rigorous, but always on your terms.'],
 ['How long does it last?', 'Two arcs are common. Some clients arrive with a specific challenge, resolve it, and graduate within six to twelve months. Others complete the foundational work and continue for years as an ongoing partnership. Neither is superior. The coach actively graduates clients when the work has run its course, and never applies pressure to stay.'],
 ['How is my privacy protected?', 'Confidentiality is established in the first minutes of the first conversation, and it is not a formality. Nothing you share is shared elsewhere. We do not publish client names, testimonials, or identifiable case material. The patterns described on this site are anonymized composites.'],
 ['What does this cost?', 'Engagements are retainer-based with one structure for everyone. The specifics are discussed directly on the discovery call. We do not publish pricing.'],
 ['Do you work with leadership teams?', 'Our focus is the senior leader, one to one. If you are interested in broader work with your team, raise it on the discovery call and we will tell you honestly whether and how we can support it.'],
];
