'use client';
import { withBase } from './EthosPath';
import { useEffect, useRef, useState } from 'react';
import { usePathname } from 'next/navigation';
import { AnimatePresence, motion, useScroll, useMotionValueEvent } from 'framer-motion';
import { Menu, X } from 'lucide-react';
export const ethosLinks = [['Home','/'],['The Methodology','/approach'],['For Leaders','/for-leaders'],['Our Coaches','/coaches'],['About','/about'],['FAQ','/faq']];
export function EthosBrand({ footer = false }: { footer?: boolean }) { return <a href={withBase('/')} aria-label="EthosQuest home" className="flex shrink-0 items-center gap-3 transition-opacity hover:opacity-80"><img src="https://ethosquest.com/eq-mark.svg" alt="" referrerPolicy="no-referrer" loading={footer ? 'lazy' : 'eager'} className={'ethos-mark w-auto object-contain ' + (footer ? 'h-[40px]' : 'h-[34px] md:h-[40px] lg:h-[44px]')} /><span className="font-accent text-[17px] font-semibold tracking-[0.12em] md:text-[19px]">EthosQuest</span></a>; }
export default function EthosNav() {
 const path = usePathname().replace(/(.)\/$/, '$1'); const isActive = (href: string) => path === href || (href === '/coaches' && path.startsWith('/coaches/')); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const { scrollY } = useScroll(); const drawer = useRef<HTMLDivElement>(null);
 useMotionValueEvent(scrollY, 'change', value => setScrolled(value > 24));
 useEffect(() => { if (!open) return; const oldFocus = document.activeElement as HTMLElement; drawer.current?.querySelector<HTMLButtonElement>('button')?.focus(); function keys(e: KeyboardEvent) { if (e.key === 'Escape') setOpen(false); if (e.key === 'Tab') { const els = drawer.current?.querySelectorAll<HTMLElement>('a,button'); if (!els?.length) return; const first = els[0]; const last = els[els.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } } const stop = (e: Event) => { if (!drawer.current?.contains(e.target as Node)) e.preventDefault(); }; document.addEventListener('keydown', keys); document.addEventListener('wheel', stop, { passive: false }); document.addEventListener('touchmove', stop, { passive: false }); return () => { document.removeEventListener('keydown', keys); document.removeEventListener('wheel', stop); document.removeEventListener('touchmove', stop); oldFocus?.focus(); }; }, [open]);
 return <><motion.header initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, ease: 'easeOut' }} className={'ethos-banner fixed inset-x-0 top-0 z-40 border-b bg-[var(--banner)] px-6 transition-all duration-500 md:px-[48px] min-[1440px]:px-[64px] ' + (scrolled ? 'border-white/10 py-3' : 'border-transparent py-5')}><div className="mx-auto flex w-full max-w-[1280px] items-center justify-between gap-6"><EthosBrand /><nav aria-label="Main navigation" className="hidden items-center gap-7 lg:flex xl:gap-9">{ethosLinks.map(([label,href]) => <a key={href} href={withBase(href)} aria-current={isActive(href) ? 'page' : undefined} className={'font-accent relative whitespace-nowrap text-[13px] uppercase tracking-[0.16em] transition-colors ' + (isActive(href) ? 'font-semibold text-white' : 'font-medium text-white/75 hover:text-white')}>{label}{isActive(href) && <motion.span layoutId="activeDot" transition={{ type: 'spring', stiffness: 300, damping: 30 }} className="absolute -bottom-2 left-0 h-px w-full bg-[#E4A3AE]" />}</a>)}</nav><a href={withBase('/private-inquiry')} className="font-accent hidden shrink-0 bg-[#F7F4EE] px-[22px] py-[12px] text-[12px] font-semibold uppercase tracking-[0.16em] text-[#132040] transition-colors hover:bg-[#9E1B34] hover:text-white lg:block">Begin Inquiry</a><button aria-label="Open navigation" aria-expanded={open} aria-controls="ethos-drawer" onClick={() => setOpen(true)} className="block border border-white/30 p-2.5 text-white lg:hidden"><Menu size={22} /></button></div></motion.header><AnimatePresence>{open && <motion.div key="drawer" ref={drawer} id="ethos-drawer" role="dialog" aria-modal="true" aria-label="Navigation" initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -16 }} transition={{ duration: 0.35, ease: 'easeInOut' }} className="fixed inset-0 z-50 flex flex-col overflow-y-auto bg-[#F7F4EE] px-6 pt-[84px] pb-12 lg:hidden"><button aria-label="Close navigation" onClick={() => setOpen(false)} className="absolute top-[20px] right-6 border border-[#132040]/20 bg-transparent p-2.5 text-[#132040]"><X size={22} /></button><nav className="mt-[32px] flex flex-col items-start gap-7">{ethosLinks.map(([label,href]) => <a key={href} href={withBase(href)} onClick={() => setOpen(false)} aria-current={isActive(href) ? 'page' : undefined} className={'font-accent text-[22px] uppercase tracking-[0.18em] ' + (isActive(href) ? 'font-semibold text-[#132040]' : 'text-[#132040]/65')}>{label}</a>)}<a href={withBase('/private-inquiry')} onClick={() => setOpen(false)} className="font-accent mt-[40px] w-full max-w-[320px] bg-[#132040] px-5 py-4 text-center text-[13px] font-semibold uppercase tracking-[0.16em] text-[#F7F4EE]">Begin Inquiry</a></nav><p className="mt-auto pt-16 text-[14px] text-[#132040]/60">Every leader needs a coach. We set the standard for what that means.</p></motion.div>}</AnimatePresence></>;
}
